- README.md
- package.json
- packages/data-table/package.json
- packages/data-table/src/components/Table.jsx
- packages/data-table/src/enhancers/hocUtils.js
- packages/data-table/src/enhancers/withDynamicCellHeights.jsx
- packages/data-table/src/enhancers/withFiltering.jsx
- packages/data-table/src/enhancers/withSorting.jsx
- packages/data-table/src/enhancers/withTableAutoSizer.jsx
- packages/data-table/src/enhancers/withWindowScroller.jsx
- packages/data-table/src/index.jsx
- packages/data-table/test/.eslintrc
- packages/data-table/test/Table_test.jsx
- packages/data-table/test/mocha.opts
- packages/demo/examples/data-table/index.jsx
- packages/demo/examples/index.jsx
- packages/demo/package.json
This PR 
- hooks up testing to the root repository and adds a simple `Table` test
- updates `Table` and (optionally) HOCs to `PureComponents`
- adds a `withWindowScroller` HOC + example
> datatable improvements

- packages/data-table/src/components/Table.jsx
- packages/data-table/src/enhancers/withFiltering.jsx
- packages/demo/examples/data-table/index.jsx
This PR adds support for custom column labels in the root @data-ui/data-table `<Table/>` (as opposed to using the column key) and fixes a bug where the default `withFiltering` filter func throws if a value is undefined/null.
> column labels + filtering bug

- packages/data-table/src/components/Table.jsx
- packages/data-table/src/enhancers/withDynamicCellHeights.jsx
- packages/data-table/src/enhancers/withFiltering.jsx
- packages/data-table/src/enhancers/withSorting.jsx
- packages/demo/examples/data-table/index.jsx
This PR 
- fixes 'cellRendererProp' in data-table <Table/>
- adds custom header example
- adds support for initial sorting in withSorting HOC
- adds debounce to withFilteringHOC
- fixes a bug with passed cellRenderers in withDynamicCellHeights
> Chris  sortable column improvements

- packages/data-table/src/enhancers/withFiltering.jsx
- packages/data-table/src/enhancers/withSorting.jsx
This PR tweaks the `withFiltering` and `withSorting` HOCs:
- checks for `window` when debouncing
- adds an optional `filterComparator` prop to `withFiltering` with a better default that handles missing values and is case-insensitive
- fixes a bug where initial sorts didn't actually sort despite the column header being updated
> `withFiltering` robustness and `withSorting` comparator

- packages/data-table/src/components/Table.jsx
this fixes a bug where column width was calling an object as a function.
> fix Table width bug

- README.md
- lerna.json
- package.json
- packages/data-table/README.md
- packages/demo/README.md
- packages/demo/examples/index.jsx
- packages/demo/examples/xy-chart/index.jsx
- packages/demo/examples/xy-chart/utils.js
- packages/demo/package.json
- packages/xy-chart/.babelrc
- packages/xy-chart/README.md
- packages/xy-chart/package.json
- packages/xy-chart/src/axis/XAxis.jsx
- packages/xy-chart/src/axis/YAxis.jsx
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/index.js
- packages/xy-chart/src/series/BarSeries.jsx
- packages/xy-chart/src/series/GroupedBarSeries.jsx
- packages/xy-chart/src/series/IntervalSeries.jsx
- packages/xy-chart/src/series/LineSeries.jsx
- packages/xy-chart/src/series/PointSeries.jsx
- packages/xy-chart/src/series/StackedBarSeries.jsx
- packages/xy-chart/src/series/VerticalBarSeries.jsx
- packages/xy-chart/src/theme.js
- packages/xy-chart/src/utils/chartUtils.js
- packages/xy-chart/src/utils/propShapes.js
- packages/xy-chart/theme.js
- packages/xy-chart/webpack.config.js
This PR adds the xy-chart package for re-usable + composable + themeable charts with x/y-axes. It leverages [vx](https://github.com/hshoff/vx) for low-level components 💯 . Check out the [examples](https://github.com/williaster/data-ui/compare/chris--xyplot?expand=1#diff-2038be74226026eb7988ec5aeedadd4a) to look at the API.
next steps:
note: proper axis display here depends on [this vx PR](https://github.com/hshoff/vx/pull/42)
cc @elibrumbaugh
> [xy-chart] Add `xy-chart` package

- packages/data-table/package.json
- packages/data-table/webpack.config.js
- packages/xy-chart/package.json
- packages/xy-chart/webpack.config.js
this PR adds [`webpack-dashboard`](https://github.com/FormidableLabs/webpack-dashboard) to the `xy-chart` and `data-table` packages for this NASA-like build dashboard:
> [dev] add webpack-dashboard

- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/enhancer/withTheme.js
- packages/xy-chart/src/index.js
- packages/xy-chart/src/utils/updateDisplayName.js
- packages/xy-chart/test/XAxis.test.js
- packages/xy-chart/test/XYChart.test.js
- packages/xy-chart/test/YAxis.test.js
- packages/xy-chart/test/withTheme.test.js
This PR adds a `withTheme` HOC for easier theme customizability. example usage:
```js
const XYChartWithTheme = withTheme(theme)(XYChart);
```
Tested in demo page + with jest.
note it also adds a sanity width/height check to `<XYChart />` for positive values.
> [xy-chart] add `withTheme` HOC

- package.json
- packages/data-table/package.json
- packages/data-table/src/components/Table.jsx
- packages/data-table/src/enhancers/withDynamicCellHeights.jsx
- packages/data-table/src/enhancers/withFiltering.jsx
- packages/data-table/src/enhancers/withSorting.jsx
- packages/data-table/src/enhancers/withTableAutoSizer.jsx
- packages/data-table/src/enhancers/withWindowScroller.jsx
- packages/data-table/webpack.config.js
- packages/demo/examples/data-table/FilterableTable.jsx
- packages/demo/examples/shared/LabeledInput.jsx
- packages/demo/package.json
- packages/demo/themes/withStyles.js
- packages/xy-chart/package.json
This PR bumps React to `^15.5.0` across all packages and updates to use `prop-types` in the `@data-ui/data-table` package. Still seeing some warnings in dev mode.
> [dependencies] update to React ^15.5.0 and use prop-types

- package.json
Reworked the React peer dep to use ^ instead of ~, as individual version restraints are problematic downstream.
Sidenote, why is lerna a peer dep? Should be a dev dep IMO.
> Support React 15.6

- package.json
- packages/data-ui-theme/.babelrc
- packages/data-ui-theme/README.md
- packages/data-ui-theme/package.json
- packages/data-ui-theme/src/color.js
- packages/data-ui-theme/src/font.js
- packages/data-ui-theme/src/index.js
- packages/data-ui-theme/src/size.js
- packages/data-ui-theme/src/svgFont.js
- packages/data-ui-theme/src/svgLabel.js
- packages/data-ui-theme/test/color.test.js
- packages/data-ui-theme/test/font.test.js
- packages/data-ui-theme/test/svgFont.test.js
- packages/data-ui-theme/test/svgLabel.test.js
- packages/demo/README.md
- packages/demo/examples/data-table/tableStyles.js
- packages/demo/examples/xy-chart/index.jsx
- packages/demo/package.json
- packages/demo/themes/DefaultTheme.js
- packages/xy-chart/README.md
- packages/xy-chart/package.json
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/theme.js
This PR consolidates themes across packages into a unified `@data-ui/theme` package. The new theme includes colors from the [open-color project](https://yeun.github.io/open-color/) which will be beneficial for more diverse color palettes.
> add `@data-ui/theme`

- packages/event-flow/src/components/App.jsx
- packages/event-flow/src/components/ControlPanel.jsx
fixes a bug where hidden event types (from legend) are filtered from the vis upon leaf node trimming. also prevents overflow in control panel when it's unnecessary.
> bugfixes for leaf node trimming + overflow in control panel

- packages/demo/examples/01-xy-chart/index.jsx
- packages/xy-chart/package.json
- packages/xy-chart/src/index.js
- packages/xy-chart/src/series/AreaSeries.jsx
- packages/xy-chart/src/series/LineSeries.jsx
- packages/xy-chart/src/utils/interpolatorLookup.js
- packages/xy-chart/test/AreaSeries.test.js
This PR adds `<AreaSeries />` to `@data-ui/xy-chart` and fixes some issues when bumping the `@vx/shape` package.
> [xy-chart] add <AreaSeries />, examples, and tests. 

- packages/data-table/package.json
- packages/data-ui-theme/package.json
- packages/event-flow/package.json
- packages/forms/package.json
- packages/radial-chart/package.json
- packages/xy-chart/package.json
also bumps `@vx/tooltip` to `0.0.137` for a `react-dom` fix.
> [build] add build `prepublish` scripts to all packages

- packages/xy-chart/src/chart/CrossHair.jsx
- packages/xy-chart/src/chart/Voronoi.jsx
This PR explicitly sets the `displayName` of the `CrossHair` and `Voronoi` components. This fixes a bug where, upon minimization, function names are lost and `XYChart` cannot accurately find and render the `CrossHair` component.
> [xy-chart] add displayName to CrossHair and Voronoi for minimization robustness

- packages/demo/examples/01-xy-chart/index.jsx
- packages/demo/examples/02-histogram/index.jsx
- packages/demo/examples/03-sparkline/BarSeriesExamples.jsx
- packages/demo/examples/03-sparkline/Example.jsx
- packages/demo/examples/03-sparkline/KitchenSinkExamples.jsx
- packages/demo/examples/03-sparkline/LineSeriesExamples.jsx
- packages/demo/examples/03-sparkline/PointsAndBandsExamples.jsx
- packages/demo/examples/shared/Spacer.jsx
- packages/demo/storybook-config/components/PropTable.jsx
- packages/xy-chart/src/chart/XYChart.jsx
This PR 
- fixes some bugs where demo was not using `displayName` when possible in `PropTables`
- sets `displayName` on `@vx` components so minimized names do not come up.
- updates `@data-ui/xy-chart` to set a `displayName` for `XYChart` to appear in `PropTables`
- fixes the flex direction of `<Spacer />` so it doesn't break all checkboxes.
> [demo] displayName fixes.

- packages/demo/examples/01-xy-chart/data.js
- packages/demo/examples/01-xy-chart/index.jsx
- packages/xy-chart/src/axis/XAxis.jsx
- packages/xy-chart/src/axis/YAxis.jsx
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/series/AreaSeries.jsx
- packages/xy-chart/src/series/BarSeries.jsx
- packages/xy-chart/src/series/CirclePackSeries.jsx
- packages/xy-chart/src/series/GroupedBarSeries.jsx
- packages/xy-chart/src/series/IntervalSeries.jsx
- packages/xy-chart/src/series/LineSeries.jsx
- packages/xy-chart/src/series/PointSeries.jsx
- packages/xy-chart/src/series/StackedBarSeries.jsx
- packages/xy-chart/src/utils/computeCirclePack.js
- packages/xy-chart/test/CirclePackSeries.test.js
- packages/xy-chart/test/computeCirclePack.test.js
this PR makes the following changes to address remaining todos in https://github.com/williaster/data-ui/pull/54
- caches scales in xychart
- use PureComponents for all series for perf
- moves yScale modifications from `CirclePackSeries` to `XYChart` so all series and axes share a single scale.
UPDATE:
- added tests for `computeCirclePack.js`
- use PureComponents for all axes for perf as well
cc @conglei
> [xy-chart] component update optimizations

- packages/demo/examples/01-xy-chart/data.js
- packages/demo/examples/01-xy-chart/index.jsx
- packages/demo/examples/03-sparkline/index.jsx
- packages/demo/package.json
- packages/xy-chart/README.md
- packages/xy-chart/package.json
- packages/xy-chart/src/annotation/HorizontalReferenceLine.jsx
- packages/xy-chart/src/axis/XAxis.jsx
- packages/xy-chart/src/axis/YAxis.jsx
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/index.js
- packages/xy-chart/src/series/AreaSeries.jsx
- packages/xy-chart/src/series/BarSeries.jsx
- packages/xy-chart/src/series/CirclePackSeries.jsx
- packages/xy-chart/src/series/GroupedBarSeries.jsx
- packages/xy-chart/src/series/IntervalSeries.jsx
- packages/xy-chart/src/series/LineSeries.jsx
- packages/xy-chart/src/series/PointSeries.jsx
- packages/xy-chart/src/series/StackedBarSeries.jsx
- packages/xy-chart/src/utils/chartUtils.js
- packages/xy-chart/src/utils/computeCirclePack.js
- packages/xy-chart/test/CirclePackSeries.test.js
- packages/xy-chart/test/HorizontalReferenceLine.test.js
- packages/xy-chart/test/PointSeries.test.js
- packages/xy-chart/test/computeCirclePack.test.js
This PR adds a `<CirclePackSeries />` which implements the [`Wang et al. Visualization of large hierarchical data by circle packing.`](https://www.researchgate.net/publication/221516201_Visualization_of_large_hierarchical_data_by_circle_packing)
Remaining items to address:
> [xy-chart] add `<CirclePackSeries />` 

- packages/demo/examples/01-xy-chart/RectPointComponent.jsx
- packages/demo/examples/01-xy-chart/index.jsx
- packages/xy-chart/src/glyph/GlyphDotComponent.jsx
- packages/xy-chart/src/index.js
- packages/xy-chart/src/series/PointSeries.jsx
- packages/xy-chart/src/utils/propShapes.js
- packages/xy-chart/test/PointSeries.test.js
Added customized renderer support for PointSeries, allowing users to pass a PointComponent to PointSeries. 
CirclePackSeries will naturally support the customized renderer too. The testing file is also updated.  
Two examples are added to show how to use customized rendering.
> Conglei customized point renderer

- packages/network/src/chart/Network.jsx
- packages/network/test/chart/Network.test.js
we need the ability to add svg filters within a network, so this PR updates `<Network />` to render any children passed within the svg.
@conglei
> [network] optionally pass children to Network to render

- packages/demo/examples/01-xy-chart/CirclePackWithCallback.jsx
- packages/demo/examples/01-xy-chart/index.jsx
- packages/xy-chart/src/series/CirclePackSeries.jsx
- packages/xy-chart/test/CirclePackSeries.test.js
This PR adds an optional `layoutCallback` prop to the `@data-ui/xy-chart` `CirclePackSeries` in order to support height updates. 
Currently a user may specify a `height` to `XYChart` but due to the circle packing algorithm, the points may overflow the container and get clipped. Therefore the callback is invoked with the `domain` and `range` of the resultant layout. 
Also adds tests and an example in storybook.
@conglei 
with and without callback:
> [xy-chart][circlepackseries] add optional layout callback 

- packages/demo/examples/01-xy-chart/ResponsiveXYChart.jsx
- packages/histogram/README.md
- packages/network/README.md
- packages/radial-chart/README.md
- packages/shared/src/enhancer/WithTooltip.js
- packages/shared/test/enhancer/WithTooltip.test.js
- packages/sparkline/README.md
- packages/xy-chart/README.md
- packages/xy-chart/src/series/GroupedBarSeries.jsx
- packages/xy-chart/src/series/StackedBarSeries.jsx
- packages/xy-chart/test/GroupedBarSeries.test.js
- packages/xy-chart/test/StackedBarSeries.test.js
this PR makes the following improvements 🚀
- [shared][tooltip] don't render a tooltip if the output of `renderTooltip` is falsy
- *breaking* [xy-chart] use `seriesKey` instead of `key` in onMouseMove event signature (relevant to StackedBarSeries and GroupedBarSeries only)
cc @alecklandgraf
> add support to hide tooltips, key => seriesKey to avoid React prop clash.

- packages/demo/examples/01-xy-chart/StatsSeriesExample.jsx
- packages/demo/examples/01-xy-chart/data.js
- packages/demo/examples/01-xy-chart/index.jsx
- packages/demo/package.json
- packages/xy-chart/README.md
- packages/xy-chart/package.json
- packages/xy-chart/src/index.js
- packages/xy-chart/src/series/BoxPlotSeries.jsx
- packages/xy-chart/src/series/ViolinPlotSeries.jsx
- packages/xy-chart/src/utils/propShapes.js
- packages/xy-chart/test/BoxPlotSeries.test.js
- packages/xy-chart/test/ViolinPlotSeries.test.js
This PR
- adds `<ViolinPlotSeries/>` and example
- adds `<BoxPlotSeries/>` and example
- bumps @vx-mock-data to 0.0.147 for stats data generation
TODO
> added stats charts in xy-chart

- packages/demo/examples/01-xy-chart/StatsSeriesExample.jsx
- packages/demo/examples/01-xy-chart/index.jsx
- packages/xy-chart/package.json
- packages/xy-chart/src/series/BoxPlotSeries.jsx
- packages/xy-chart/src/series/ViolinPlotSeries.jsx
- packages/xy-chart/test/BoxPlotSeries.test.js
- packages/xy-chart/test/ViolinPlotSeries.test.js
This PR adds the following
🏆  Enhancements
- Exposes the following props on `<BoxplotSeries />` to enable more customization: `containerProps`, `boxProps`, `outlierProps`, `minProps`, `maxProps`, `medianProps`
- Adds the ability to set mouse events on the boxplot container or on its component parts (whiskers, etc)
- Consolidates some of examples for [demo][boxplot]:
TODO
> [boxplot] add support for boxplot container events

- packages/demo/examples/01-xy-chart/index.jsx
- packages/histogram/README.md
- packages/histogram/package.json
- packages/histogram/src/index.js
- packages/network/package.json
- packages/network/src/index.js
- packages/radial-chart/README.md
- packages/shared/package.json
- packages/shared/src/enhancer/WithTooltip.js
- packages/shared/test/enhancer/WithTooltip.test.js
- packages/sparkline/README.md
- packages/xy-chart/README.md
- packages/xy-chart/package.json
- packages/xy-chart/src/index.js
🏆  Enhancements
- Allows additional customization Adds `tooltipProps` to the `<WithTooltip />`which will be passed to its `TooltipComponent` (and adds example in demo)
- Exposes `@vx/responsive`'s [new observer-based `<ParentSize />` HOC](https://github.com/hshoff/vx/pull/198)
🐛  Bug fix
- bumps `@vx/tooltip` to 0.0.148 for [bounds bug fix](https://github.com/hshoff/vx/pull/204) 
TODO
> [shared] Expose tooltip props

- packages/demo/examples/01-xy-chart/LineSeriesExample.jsx
- packages/xy-chart/src/axis/XAxis.jsx
- packages/xy-chart/src/axis/YAxis.jsx
- packages/xy-chart/src/utils/findClosestDatums.js
- packages/xy-chart/test/axis/XAxis.test.js
- packages/xy-chart/test/axis/YAxis.test.js
This PR does the following 
🐛 Bug Fix
- Fixes a bug where `tickLabelProps` is not used when passed in either `<XAxis />` or `<YAxis />`. This prop enables per-tick styles so is importanté!
- Improves the logic for finding closest `datum`s across series when `eventTrigger=container` by considering `deltaX` from `mouseX` in addition to `deltaY` from `mouseY`. If `deltaX` is not considered, the "closest" `datum` in the `y` dimension might belong to a series whose nearest `x` value is quite far from `mouseX` (if the other data points are `null`, for instance):
**Before**
**After**
> [xy-chart] consider deltaX in findClosestDatums, fix tickLabelProps bug in <*Axis />

- packages/histogram/src/axis/YAxis.jsx
`innerHeight` was being referenced in the guard at the top of the component, but since it wasn't destructured from props in the func param, it was undefined.
🐛 Bug Fix
> 🐛  added `innerHeight`  to props destructure

- packages/demo/examples/04-network/ExpandableNetwork.jsx
- packages/demo/examples/04-network/ExpandableNetworkWithCustomizedLayout.jsx
- packages/demo/examples/04-network/NetworkWithCustomizedRenderer.jsx
- packages/network/README.md
- packages/network/src/chart/Network.jsx
- packages/network/test/chart/Network.test.js
Mouse events renamed
- `onNodeClick` => `onClick`
- `onNodeMouseEnter` => `onMouseEnter`
- `onNodeMouseLeave` => `onMouseLeave`
🏆 Enhancements
- allow user to wrap `<Network />` in WithTooltip to support programmatic triggering and custom tooltip logic
- add `eventTriggerRefs` callback to support programmatic tooltip triggering
- add `snapToTooltipX` and `snapToTooltipY` support
- updates readme with new props
🏡Internal
- fix broken network example
- remove unused/add new `Network.propTypes`
cc @conglei
> [network] tooltip and mouse event updates

- packages/shared/src/components/FocusBlurHandler.jsx
- packages/shared/src/index.js
- packages/shared/test/components/FocusBlurHandler.test.jsx
- packages/shared/test/enhancer/WithTooltip.test.js
- packages/xy-chart/README.md
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/series/AreaSeries.jsx
- packages/xy-chart/src/series/BarSeries.jsx
- packages/xy-chart/src/series/BoxPlotSeries.jsx
- packages/xy-chart/src/series/IntervalSeries.jsx
- packages/xy-chart/src/series/LineSeries.jsx
- packages/xy-chart/src/series/PointSeries.jsx
- packages/xy-chart/src/series/ViolinPlotSeries.jsx
- packages/xy-chart/test/axis/XAxis.test.js
- packages/xy-chart/test/series/AreaSeries.test.js
- packages/xy-chart/test/series/BarSeries.test.js
- packages/xy-chart/test/series/BoxPlotSeries.test.js
- packages/xy-chart/test/series/IntervalSeries.test.js
- packages/xy-chart/test/series/LineSeries.test.js
- packages/xy-chart/test/series/PointSeries.test.js
- packages/xy-chart/test/series/ViolinPlotSeries.test.js
🏆 Enhancements
This PR is the first to address #86 to begin to make tooltips accessible to keyboard-only users via support of `onFocus` and `onBlur` props.
This PR
- adds the `@data-ui/shared` `<FocusBlurHandler />` handler that wraps mouse target nodes in an `<a />` element, which [seems to be the most reliable way to support focusing in svg 1.1/1.2](https://allyjs.io/tutorials/focusing-in-svg.html)
- adds `onFocus` and `onBlur` support to the following `<*Series />` components (the remainder depend on `@vx` exposing hooks to series dom nodes (to wrap in `<a />`s)
| Series  | `onFocus` + `onBlur` support added |
| ------------- | ------------- |
| AreaSeries  | x |
| BarSeries  | x |
| BoxPlotSeries  | x |
| CirclePackSeries  | x |
| IntervalSeries | x |
| LineSeries  | x |
| PointSeries …
> [accessibility] add FocusBlurHandler, add to most xy-chart series

- packages/xy-chart/test/series/AreaSeries.test.js
🐛 Bug Fix
Fixes a broken `AreaSeries` test introduced by `FocusBlurHandler` (which changed the logic to always render a `LinePath` for tab-ability).
> [xy-chart][tests] fix areaseries test

- packages/demo/examples/04-network/ExpandableNetwork.jsx
- packages/demo/examples/04-network/index.jsx
- packages/network/README.md
- packages/network/src/chart/Network.jsx
🏆 Enhancements
In this PR, the aspectratio control is added. For some layout algorithm, we don't need to keep the original aspect ratio for responsive scaling. In `<Network />`, `keepAspectRatio` is added. 
🐛 Bug Fix
Before, the layout will be run in constructor. However, in some case, when the layout algorithm is fast enough, the callback function with `setGraphState` will be called before the component is mounted, which will cause the graph not properly rendered. 
In this PR, the initial layout is called in `componentDidMount`. 
@williaster
> [network] changed the init layout in mounted, and add aspectraio control

- packages/demo/examples/01-xy-chart/computeForceBasedCirclePack.js
- packages/demo/examples/01-xy-chart/data.js
- packages/demo/examples/01-xy-chart/index.jsx
- packages/demo/package.json
- packages/xy-chart/README.md
- packages/xy-chart/src/series/CirclePackSeries.jsx
🏆 Enhancements
In this PR, we exposed circle packing layout as a prop so users can pass their own layout algorithm into circle packing charts. In the demo, we show an example of a customized layout algorithm. 
Updated the documentation.
@williaster
> exposed circle packing layout as a prop

- packages/shared/src/components/FocusBlurHandler.jsx
[shared]
🐛 Bug Fix
- prefer `role="presentation"` instead of `role="button"` on `<FocusBlurHandler />` to fix [this a11y axe violation](https://dequeuniversity.com/rules/axe/2.5/button-name?application=axeAPI)
tested locally by sym-linking to our internal component library that flags axe violations.
cc @backwardok
> [shared] role=button => role=presentation on FocusBlurHandler

- packages/demo/examples/02-histogram/HistogramPlayground.jsx
- packages/demo/examples/02-histogram/index.jsx
- packages/histogram/README.md
- packages/histogram/src/chart/Histogram.jsx
- packages/histogram/src/series/BarSeries.jsx
- packages/histogram/src/series/animated/AnimatedBarSeries.jsx
- packages/histogram/test/components/AnimatedBarSeries.test.js
- packages/histogram/test/components/BarSeries.test.js
Fixes #102 
🏆 Enhancements
- Adds `onClick` support to `BarSeries` and `AnimatedBarSeries`
- `onClick` and `onMouseMove` functions are passed `index` in addition to `data`, `datum`, `event`, and `color`
cc @bmantoni
> [histogram] add onClick support to BarSeries

- packages/data-table/package.json
- packages/data-ui-theme/package.json
- packages/event-flow/package.json
- packages/forms/package.json
- packages/histogram/package.json
- packages/network/package.json
- packages/radial-chart/package.json
- packages/shared/package.json
- packages/sparkline/package.json
- packages/xy-chart/package.json
🏠 Internal
I'd specified `"node": ">=8.10.0"` in all packages for compatibility with beemo. However, this is only a dev requirement so I'm moving it to just the root package.
> [packages/*] only specify node engine in root

- packages/demo/package.json
- packages/shared/package.json
🐛 Bug Fix 
🏠 Internal
fixes a bug for local dev where `demo` is broken because
1.  it doesn't have a `@data-ui/shared` dependency and 
2. `@data-ui/shared` was not building itself on a fresh install due to a missing `prepublish` script.
cc @conglei
> add @data-ui/shared as a @data-ui/demo dep, add prepublish scrip to @data-ui/shared

- packages/demo/examples/02-histogram/renderHistogramTooltip.jsx
- packages/histogram/src/chart/Histogram.jsx
- packages/histogram/src/series/BarSeries.jsx
- packages/histogram/src/series/animated/AnimatedBarSeries.jsx
- packages/histogram/src/utils/binNumericData.js
- packages/histogram/src/utils/shallowCompareObjectEntries.js
- packages/histogram/test/utils/shallowCompareObjectEntries.test.js
🐛 Bug Fix
This fixes #100 and #118 which both arise due to an issue with binning for numeric, raw data. 
Previously an extra bin was generated, which was then trimmed. In the cases highlighted in the two issues, this resulted in errors or inaccurate bins/bin counts.
When there is only one raw data value (#100):
```javascript
<Histogram
ariaLabel=""
height={250}
width={500}
>
<BarSeries rawData={[0, 0, 0, 0]} />
<XAxis />
<YAxis />
</Histogram>
```
0s and 1s (#118)
```javascript
<Histogram
ariaLabel=""
height={250}
width={500}
>
<BarSeries rawData={[1, 1, 1, 1, 0, 0]} />
<XAxis />
<YAxis />
</Histogram>
```
Note that the binning here is due to the default `binCount={10}`, set to `2` instead:
cc @kaiyoma @PAK90
> [histogram] don't trim (or make it necessary to trim) numeric data bins

- packages/histogram/package.json
- packages/histogram/src/utils/binNumericData.js
🐛 Bug Fix
Fix for `histogram` when the last numeric bin computed for raw data has equal start/end, was incorrectly setting the upper bound.
> [histogram] fix edge bin, add dev script

- packages/demo/examples/01-xy-chart/BrushableLineChart.jsx
- packages/demo/examples/01-xy-chart/ResponsiveXYChart.jsx
- packages/demo/examples/02-histogram/index.jsx
- packages/histogram/src/utils/binNumericData.js
- packages/xy-chart/src/enhancer/withTheme.jsx
- packages/xy-chart/test/enhancer/withTheme.test.js
🐛 Bug Fix
[xy-chart]
- the `withTheme` HOC would override the passed theme with the empty default theme from `XYChart`. To support overrides, combine the two objects. 
[histogram]
- in the case that there's one un-binned numeric value, enforce a bin length of 1
> misc bug fixes

- packages/demo/examples/01-xy-chart/BrushableLineChart.jsx
- packages/xy-chart/src/annotation/VerticalReferenceLine.jsx
- packages/xy-chart/src/axis/YAxis.jsx
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/test/axis/YAxis.test.js
- packages/xy-chart/test/chart/XYChart.test.js
🏆 Enhancements
- Improves y-axis label wrapping logic to use full chart height, not inner height
- Enable setting `labelOffset` on `XAxis` and `YAxis` labels instead of setting a constant `0.7 * margin.left/right` and `0` for `YAxis` and `XAxis` respectively
- Adds tests for these things
> [xy-chart] wrap y-axis label based on height not inner height

- packages/demo/examples/01-xy-chart/HorizontalBarChart.jsx
- packages/demo/examples/01-xy-chart/LineSeriesExample.jsx
- packages/demo/examples/shared/Checkbox.jsx
- packages/demo/examples/shared/WithToggle.jsx
- packages/xy-chart/README.md
- packages/xy-chart/src/chart/CrossHair.jsx
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/test/chart/CrossHair.test.js
🏆 Enhancements
This PR adds support for rendering  multiple circles on the `XYChart` `Crosshair` component when `XYChart`'s `eventTrigger='container'` (which passes `series` to support multiple circles). You can set styles per-circle as shown in the example:
TODO
> [xy-chart][crosshair] support multiple circles

- .travis.yml
- packages/data-table/package.json
- packages/data-ui-theme/package.json
- packages/demo/package.json
- packages/event-flow/package.json
- packages/forms/package.json
- packages/histogram/package.json
- packages/network/package.json
- packages/radial-chart/package.json
- packages/shared/package.json
- packages/sparkline/package.json
- packages/xy-chart/package.json
🏠 Internal
- bump to `@data-ui/build-config@^0.0.12` which fixes a coverage collection issue
-  use `codecov` not `coveralls`
> [build] @data-ui/build-config@^0.0.12, use codecov not coveralls

- packages/demo/examples/01-xy-chart/BrushableLineChart.jsx
- packages/demo/examples/01-xy-chart/HorizontalBarChart.jsx
- packages/demo/examples/01-xy-chart/LineSeriesExample.jsx
- packages/xy-chart/src/selection/Brush.jsx
- packages/xy-chart/src/utils/brush/Brush.jsx
- packages/xy-chart/src/utils/brush/BrushSelection.jsx
- packages/xy-chart/src/utils/chartUtils.js
- packages/xy-chart/test/selection/Brush.test.jsx
- packages/xy-chart/test/utils/chartUtils.test.js
🏆 Enhancements
Exposed the reset function to Brush and added an example to show how to use it. 
Enabled the click event for `Brush`.
Exposed starting point of brush to `onBrushStart` . 
🐛 Bug Fix
🏠 Internal
> [UI]added reset support and click support for Brush

- packages/data-table/package.json
- packages/data-ui-theme/package.json
- packages/histogram/package.json
- packages/network/package.json
- packages/radial-chart/package.json
- packages/shared/package.json
- packages/shared/src/enhancer/WithTooltip.jsx
- packages/sparkline/package.json
- packages/sparkline/src/chart/Sparkline.jsx
- packages/sparkline/src/series/LineSeries.jsx
- packages/sparkline/src/utils/findClosestDatum.js
- packages/xy-chart/package.json
- packages/xy-chart/src/chart/CrossHair.jsx
- packages/xy-chart/src/chart/Voronoi.jsx
- packages/xy-chart/src/chart/XYChart.jsx
- packages/xy-chart/src/selection/Brush.jsx
- packages/xy-chart/src/series/AreaSeries.jsx
- packages/xy-chart/src/series/LineSeries.jsx
- packages/xy-chart/src/series/StackedAreaSeries.jsx
- packages/xy-chart/src/utils/findClosestDatum.js
- packages/xy-chart/src/utils/findClosestDatums.js
- packages/xy-chart/src/utils/propShapes.js
- packages/xy-chart/src/utils/sharedSeriesProps.js
- packages/xy-chart/test/utils/findClosestDatum.test.js
- packages/xy-chart/test/utils/findClosestDatums.test.js
🐛 Bug Fix
This fixes #137 where tooltips have incorrect offsets when using `<YAxis orientation="left" />` or `<XAxis orientation="top" />`. 
This bug occurs specifically with `<AreaSeries />` and `<LineSeries />`, and the data point that is highlighted in these instances is approximately `margin.left` to the right of the point you expect it to be (for `<YAxis orientation="left" />`) or `margin.top` below the point you expect it to be (for `<XAxis orientation="top" />`).
cc @jhofstede
> 🐛[xy-chart] fix top/left tooltip offset

- packages/demo/examples/01-xy-chart/HorizontalBarChart.jsx
- packages/xy-chart/README.md
- packages/xy-chart/package.json
- packages/xy-chart/src/annotation/HorizontalReferenceLine.jsx
- packages/xy-chart/src/annotation/Text.jsx
- packages/xy-chart/src/annotation/VerticalReferenceLine.jsx
- packages/xy-chart/src/index.js
- packages/xy-chart/src/series/BarSeries.jsx
- packages/xy-chart/src/series/PointSeries.jsx
- packages/xy-chart/test/axis/YAxis.test.js
- packages/xy-chart/test/series/BarSeries.test.js
- packages/xy-chart/test/series/PointSeries.test.js
🏆 Enhancements
- Adds support to `<BarSeries />` for rendering labels via the `renderLabel` and `defaultLabelProps` props 
- by default, if a `datum` has a `label` property, it will have a label rendered out of the box using the amazing `@vx/text` `<Text />` component (which wraps `svg` text, etc.). labels are always rendered on top of the `Bar`s themeselves.
- The label has "smart" default aesthetics (taking from the `@data-ui` theme), text anchors, and wrapping behavior, but you can override them by setting `defaultLabelProps` to your own object. 
- to support full label customization, users can define a `renderLabel` function with the signature `({ datum, index, labelProps }) => node`. `labelProps` includes all values from `defaultLabelProps` as well as "smart" default values for …
> [xy-chart] add `renderLabel` to `<BarSeries />`

- packages/data-ui-theme/package.json
🏠 Internal
Not sure how this passed through the cracks and passed  previously, but this fixes the `babel-jest` path for the `theme` package
> [theme][tests] fix babel-jest path

- packages/data-ui-theme/package.json
🐛 Bug Fix
In the `babel 7` upgrade (#141) I mistakenly put the `@babel/runtime@7` dep in dev dependencies for `@data-ui/theme`, and left `babel-runtime@6` 🤦‍♂️  which may cause issues for downstream consumers.
@etripier
> [theme] `babel-runtime@6` => `@babel/runtime@7`

- packages/data-table/.gitignore
- packages/data-ui-theme/.gitignore
- packages/demo/.gitignore
- packages/event-flow/.gitignore
- packages/forms/.gitignore
- packages/histogram/.gitignore
- packages/network/.gitignore
- packages/radial-chart/.gitignore
- packages/shared/.gitignore
- packages/sparkline/.gitignore
- packages/xy-chart/.gitignore
🐛 Bug Fix
This fixes #151 where `yarn check` fails for `@data-ui/histogram` due to the `yarn.lock` file mistakenly being included in the published npm package. 
Previously lock files were ignored in the monorepo root, but `lerna` expects these to be set per-package (see [here](https://github.com/lerna/lerna/issues/296)).
cc @kaiyoma
> [build] .gitignore lock files per-package

- packages/data-table/package.json
- packages/data-ui-theme/package.json
- packages/demo/package.json
- packages/event-flow/package.json
- packages/forms/package.json
- packages/histogram/package.json
- packages/network/package.json
- packages/radial-chart/package.json
- packages/shared/package.json
- packages/sparkline/package.json
- packages/xy-chart/package.json
🏠 Internal
Removes the `@babel/runtime` dep across packages as we no longer use it in our `@beemo`-generated `babel.config.js`. This may be causing an issue in `0.0.72`
> [build] remove @babel/runtime dep

- packages/data-table/package.json
- packages/data-ui-theme/package.json
- packages/demo/examples/01-xy-chart/HorizontalBarChart.jsx
- packages/demo/package.json
- packages/event-flow/package.json
- packages/forms/babel.config.js
- packages/forms/package.json
- packages/histogram/package.json
- packages/network/package.json
- packages/radial-chart/package.json
- packages/shared/package.json
- packages/sparkline/package.json
- packages/xy-chart/package.json
- packages/xy-chart/src/utils/brush/Brush.jsx
- packages/xy-chart/test/axis/YAxis.test.js
🏠 Internal
💥 [possibly breaking] Previously we've configured `@babel/preset-env` `useBuiltIns` to `"usage"` which has caused issues with `core-js` deps. Rather than adding a `core-js` dep we'll punt on polyfills to consumers 
Note: this doesn't apply to `event-flow` because it is bundled as a mini app essentially.
> [build][babel] let consumers polyfill

- packages/histogram/src/utils/computeDomainsFromBins.js
- packages/histogram/test/utils/computeDomainsFromBins.test.js
🏆 Enhancements
If the user provides a set of bin values, and these match the domain of
the data, use these under the assumption that the user has sorted the
bin values according to their preferred order.
> Use provided bin values for bin domains.

- packages/xy-chart/src/axis/XAxis.jsx
🏆 Enhancements
* Add `labelOffset` to `XAxis` props. Use default value of `14` from the underlying `vx`.
> Add labelOffset to XAxis props

- packages/demo/examples/02-histogram/renderHistogramTooltip.jsx
- packages/histogram/src/utils/binNumericData.js
🏆 Enhancements
This PR updates the computation for numeric bins in `@data-ui/histogram` to squash the last two bins together when the thresholds of the **_last bin_** are equal to the upper threshold of the **_second to last_** bin. Without doing this the results can be quite confusing as pointed out by some `Superset` users.
example, given the following raw data `[0, 0, 1, 2, 3, 9, 9, 10, 10, 10]` (note **`10`** is the max value) and `binCount=10`
We get the following _`11 bins`_
or with `binCount=20` (and _`21`_ resultant bins 🤔 )
[This issue](https://github.com/d3/d3-array/issues/46#issuecomment-269873644) explains this behavior
> given `n` bins, `n+1` bin thresholds are produced. 
> the last bin (bins[thresholds.length]) contains any value greater than or equal to the last threshold …
> [histogram] squash end-inclusive histogram bins

- packages/shared/src/enhancer/WithTooltip.jsx
🏆 Enhancements
🐛 Bug Fix
Fix issue #167, after this fix, a focus event won't show the tooltip anymore.
An alternative fix I tried was to add `&& event.type !== 'focus'` to the condition here https://github.com/williaster/data-ui/blob/master/packages/shared/src/enhancer/WithTooltip.jsx#L71. In that case clicking on a bar for the first time (focusing it) would move the position of the bar. What do you think about this? @williaster 
🏠 Internal
> [shared]: fix issue #167

- packages/xy-chart/package.json
vx/text creates an invisible svg to measure text width, but in previous versions doesn't make the svg `absolute` positioned.
https://github.com/hshoff/vx/blame/013f2abd5fee794ea0c246e9d1de08559817af68/packages/vx-text/src/util/getStringWidth.js
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
> Bump @vx/text version

- packages/histogram/src/axis/XAxis.jsx
- packages/histogram/src/axis/YAxis.jsx
🐛 Bug Fix
Applies the same fix from #82 for histogram axes as well.
Closes #183
> Histogram ticklabelprops fix

- packages/xy-chart/src/chart/XYChart.jsx
🐛 Bug Fix
Fixes #189 by allowing `rangePadding` override on `Axis` components.
> fix(xy-chart): allow rangePadding override

- packages/demo/examples/01-xy-chart/HorizontalBarChart.jsx
- packages/demo/examples/01-xy-chart/index.jsx
- packages/xy-chart/src/series/BarSeries.jsx
- packages/xy-chart/test/series/BarSeries.test.js
🐛 Bug Fix
This fixes an issue in `@data-ui/xy-chart` where negative `y` values render incorrectly for `BarSeries`. Updates the demo to include such `y` values.
**Before** (look at tooltips)
**After** 
@conglei @kristw
> fix(xy-chart/BarSeries): fix negative value rendering, update stories
