williaster/data-ui

packages/data-table/src/enhancers/withDynamicCellHeights.jsx, packages/data-table/src/enhancers/withSorting.jsx
=> fix sort comparator

packages/data-table/package.json, packages/demo/package.json, packages/xy-chart/package.json
=> support React 15.6 across packages. make lerna a dev dep.

packages/histogram/README.md
The sample histogram code needed a couple updates. I couldn't find `aspectRatio` anywhere and didn't know if this should pull in `fill`, `stroke`, etc from the theme.
Also there seemed to be a redundant bar series.
=> [docs][histogram] updates example code

packages/demo/examples/04-network/data.js, packages/network/src/chart/Network.jsx, packages/network/src/layout/atlasForce.js, packages/network/test/chart/Network.test.js
In this PR, The layout algorithm is refined by better scaling the size of graph to fit the canvas size.
=> Conglei graph refine

packages/demo/examples/04-network/ExpandableNetwork.jsx, packages/demo/examples/04-network/NetworkWithCustimizedRenderer.jsx, packages/demo/examples/04-network/data.js, packages/demo/examples/04-network/index.jsx, packages/demo/storybook-config/components/GoogleAnalytics.jsx, packages/network/src/chart/Network.jsx, packages/network/src/index.js, packages/network/test/chart/Link.test.js, packages/network/test/chart/Links.test.js, packages/network/test/chart/Network.test.js, packages/network/test/chart/Node.test.js, packages/network/test/chart/Nodes.test.js, packages/network/test/layout/atlasForce.test.js
this PR
- updates Network to show computing message whenever the graph layout is recomputing
- calls done in async tests
- exports default Node and Link components
@conglei
=> [network] pre-release

package.json, packages/histogram/package.json, packages/radial-chart/package.json, packages/sparkline/package.json, packages/xy-chart/package.json
hoping this will fix the build 🤞
=> [deps] update root to react 16, enzyme 3.1.0 across packages

packages/data-table/package.json, packages/demo/storybook-config/webpack.config.js, packages/event-flow/package.json, packages/forms/package.json, packages/radial-chart/package.json, packages/xy-chart/package.json
this pr 
- removes some unnecessary webpack flags (`--optimize-minimize` which is redundant with `-p`) 
- updates the storybook webpack config logic to _only_ remove uglifyjs in dev mode. This fixes some react errors in the published storybook.
=> [build] fix react errors in published storybook

packages/demo/examples/04-network/ExpandableNetworkWithCustimizedLayout.jsx, packages/demo/examples/04-network/ExpandableNetworkWithCustomizedLayout.jsx, packages/demo/examples/04-network/index.jsx, packages/network/src/chart/Network.jsx, packages/network/src/layout/atlasForce.js, packages/network/test/layout/atlasForce.test.js
In this PR, customizable layout is added for network visualization. use can pass a layout instance to the Network component.
=> Conglei  network  customizable  layout

packages/sparkline/README.md
Setting up env for superset-ui and realized the example wasn't working str8 of the box so I fixed inside my storyboard and wanted to run the changes back into master
@williaster Let me know what you think?
=> Update Sparkline README.md

packages/histogram/src/axis/YAxis.jsx
🐛 Bug Fix
fixing failing test from merging #85
=> [histogram][yaxis] remove innerHeight prop to fix failing tests

packages/demo/examples/01-xy-chart/ResponsiveXYChart.jsx, packages/xy-chart/src/utils/computeCirclePack.js
🐛 Bug Fix
For circle packing algorithm, when trying to find a optimum position, sometime it will get a position out of the x range. In this pr, an constrain is added to get void of this situation. 
Before: 
After:
=> Improved circle packing algorithm

packages/demo/examples/04-network/ExpandableNetworkWithCustomizedLayout.jsx, packages/network/README.md, packages/network/src/chart/Network.jsx, packages/network/test/chart/Network.test.js
🏆 Enhancements
This PR exposes the flexibility for the layout algorithms themselves to handle scale to fit functionality. 
Updated the documentation for the new parameter. 
🐛 Bug Fix
🏠 Internal
=> allow layout algirhtms to handle scale to fit

packages/histogram/src/series/BarSeries.jsx, packages/histogram/src/series/DensitySeries.jsx
🐛 Bug Fix
Should fix #104 which is only seen in production and I think is probably caused by missing names upon minification breaking [this line](https://github.com/williaster/data-ui/blob/master/packages/histogram/src/chart/Histogram.jsx#L167).
cc @pandeyshashank
=> [histogram] add displayName to DensitySeries

packages/xy-chart/README.md, packages/xy-chart/package.json, packages/xy-chart/src/annotation/VerticalReferenceLine.jsx, packages/xy-chart/src/axis/YAxis.jsx, packages/xy-chart/src/index.js, packages/xy-chart/src/series/LineSeries.jsx, packages/xy-chart/test/annotation/VerticalReferenceLine.test.js
🏆 Enhancements
This PR  
- adds a `VerticalReferenceLine` component to the `xy-chart` package to complement the existing `HorizontalReferenceLine`.
- Uses the `@vx/text` `Text` component for labels in `VerticalReferenceLine` and `HorizontalReferenceLine` components to support better wrapping, etc., out of the box.
Demo (not committed)
TODO
=> [xy-chart] add <VerticalReferenceLine />, use @vx/text for <*ReferenceLine /> labels

packages/demo/examples/01-xy-chart/BrushableLinkedLineCharts.jsx, packages/demo/examples/01-xy-chart/data.js, packages/demo/examples/01-xy-chart/index.jsx, packages/xy-chart/src/axis/XAxis.jsx, packages/xy-chart/src/axis/YAxis.jsx
🏆 Enhancements
- [xy-chart] allow string type tick values 
- [demo][xy-chart] add linked chart brushing example
=> [xy-chart] better tick values props + linked brush demo

packages/network/src/chart/Link.jsx, packages/network/src/chart/Network.jsx, packages/network/test/chart/Network.test.js
🏆 Enhancements
Expose interactions on links.
🐛 Bug Fix
🏠 Internal
=> expose interactions on link

.travis.yml, packages/demo/package.json
🏠 Internal
- add linting to travis build
- add demo package to build matrix
cc @conglei
=> [travis] lint as build step, add demo package to matrix

packages/xy-chart/README.md
Tiny PR to fix typo.
I just started using this library recently and love it! Thanks :)
=> Fix typo in package Readme

packages/demo/package.json, packages/event-flow/package.json, packages/forms/package.json, packages/histogram/package.json, packages/network/package.json, packages/radial-chart/package.json, packages/shared/package.json, packages/sparkline/package.json, packages/xy-chart/package.json
🏠 Internal
Upgrade to theoretical next patch version of @data-ui/build-config.
=> upgrade to 0.0.28

packages/histogram/src/utils/computeDomainsFromBins.js, packages/histogram/test/utils/computeDomainsFromBins.test.js, packages/shared/src/enhancer/WithTooltip.jsx, packages/xy-chart/src/chart/XYChart.jsx, packages/xy-chart/src/series/BarSeries.jsx, packages/xy-chart/src/series/PointSeries.jsx
🏠 Internal
Fixes lint errors revealed in the failed build of #159
=> [shared, xychart] fix eslint errors from version bump

packages/data-table/package.json, packages/data-ui-theme/package.json, packages/demo/package.json, packages/event-flow/package.json, packages/forms/package.json, packages/histogram/package.json, packages/network/package.json, packages/radial-chart/package.json, packages/shared/package.json, packages/sparkline/package.json, packages/xy-chart/package.json
🏠 Internal
Fixes the `Beemo` build issue reported in #162
=> [build-config] to ^0.0.37

packages/data-table/package.json, packages/data-ui-theme/package.json, packages/demo/package.json, packages/event-flow/package.json, packages/forms/package.json, packages/histogram/package.json, packages/network/package.json, packages/radial-chart/package.json, packages/shared/package.json, packages/sparkline/package.json, packages/xy-chart/package.json
🏠 Internal
Bumping to `@data-ui/build-config@^0.0.40` should fix a problem with `boost` which is not pinned in `Beemo`, which we use for build-config.
This is currently breaking the build as reported in #165
=> `@data-ui/build-config@^0.0.40`

packages/event-flow/package.json
🏠 Internal
- [event-flow][lint] warn on `compat/compat`
=> [event-flow][lint] warn on compat/compat

packages/data-ui-theme/README.md
=> Update readme to include allColors export

packages/xy-chart/package.json
=> Update package.json to use @vx/axis 0.0.175+

packages/demo/examples/01-xy-chart/ScatterWithHistograms.jsx, packages/demo/examples/03-sparkline/KitchenSinkExamples.jsx, packages/demo/examples/05-radial-chart/index.jsx, packages/histogram/src/axis/YAxis.jsx, packages/xy-chart/src/chart/XYChart.jsx, packages/xy-chart/src/series/BarSeries.jsx, packages/xy-chart/src/series/PointSeries.jsx, packages/xy-chart/src/utils/propShapes.js
🏠 Internal
- fix(Histogram/YAxis): Use arrow func
- Also verifying fixing the build
=> fix(Histogram/YAxis): Use arrow func

packages/xy-chart/README.md
=> fix XYChart import

packages/data-table/test/withDynamicCellHeights.test.js, packages/data-table/test/withFiltering.test.js, packages/data-table/test/withSorting.test.js, packages/data-table/test/withTableAutoSizer.test.js, packages/data-table/test/withWindowScroller.test.js, packages/histogram/package.json, packages/network/package.json, packages/sparkline/package.json, packages/xy-chart/package.json, packages/xy-chart/src/composer/ParentSize.jsx, packages/xy-chart/src/enhancer/withParentSize.js, packages/xy-chart/src/enhancer/withScreenSize.js
🐛 Bug Fix
Bumps `@vx/responsive` to the latest for some bug fixes across packages in downstream consumers
=> deps: bump @vx/responsive to 0.0.192
